name: Sync release version to package.json (npm)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  sync-version:
    uses: decentraland/platform-actions/.github/workflows/sync-release-version.yml@main
