name: CI/CD on main branch

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true

jobs:
  cd:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: ${{ inputs.service-name }}
    secrets: inherit
