name: build-app

on:
  workflow_call:

jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: create .env
        run: echo "" >> .env
      - name: build
        run: yarn build
      - name: test
        run: yarn test
