name: CI/CD on PR for apps

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true

jobs:
  build-quay:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: ${{ inputs.service-name }}
    secrets: inherit
  title:
    uses: decentraland/actions/.github/workflows/validate-pr-title.yml@main
