name: CI/CD on main branch

on:
  workflow_call:
    inputs:
      dockerfile-url:
        required: false
        type: string
      service-name:
        required: true
        type: string
      deployment-environment:
        required: false
        type: string
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true

jobs:
  dockerfile:
    if: ${{ inputs.dockerfile-url }}
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O Dockerfile ${{ inputs.dockerfile-url }}

  cd:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: ${{ inputs.service-name }}
      deployment-environment: ${{ inputs.deployment-environment }}
      docker-tag: next
    secrets: inherit
