name: build-app

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '18.x'
        description: 'Node.js version to use'

      node-version-file:
        required: false
        type: string
        description: "Path to the file containing the Node.js version to use (e.g., .nvmrc, .node-version)"

jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version-file == '' && inputs.node-version || '' }}
          node-version-file: ${{ inputs.node-version-file }}
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version-file == '' && inputs.node-version || '' }}
          node-version-file: ${{ inputs.node-version-file }}
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: create .env
        run: echo "" >> .env
      - name: build
        run: yarn build
      - name: test
        run: yarn test --coverage
      - name: hide coveralls if repo is private
        id: repo-visibility
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }})

          # Validate and parse JSON response
          if echo "$RESPONSE" | jq -e . >/dev/null 2>&1; then
              IS_PRIVATE=$(echo "$RESPONSE" | jq -r '.private')
          else
              echo "Error: API response is not valid JSON or malformed."
              exit 1
          fi

          echo $IS_PRIVATE
          # Set environment variable for coveralls
          if [ "$IS_PRIVATE" = 'true' ]; then
              echo "continue-coveralls=false" >> $GITHUB_OUTPUT
          else
              echo "continue-coveralls=true" >> $GITHUB_OUTPUT
          fi

      - name: report coverage
        if: steps.repo-visibility.outputs.continue-coveralls == 'true'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info

          
