name: Publish 'latest' image

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      deployment-environment:
        required: false
        type: string
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true

jobs:
  cd:
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    with:
      service-name: ${{ inputs.service-name }}
      deployment-environment: ${{ inputs.deployment-environment }}
      docker-tag: latest ${{ github.event.release.tag_name }}
      build-args: CURRENT_VERSION=${{ github.event.release.tag_name }}
    secrets: inherit
