name: CI/CD on PR for apps

on:
  workflow_call:
    inputs:
      dockerfile-url:
        required: false
        type: string
      service-name:
        required: true
        type: string
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true

jobs:
  build-quay:
    steps:
    - name: wget
      if: ${{ inputs.dockerfile-url }}
      uses: wei/wget@v1
      with:
        args: -O Dockerfile ${{ inputs.dockerfile-url }}
    - name: build
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
      with:
        service-name: ${{ inputs.service-name }}
        docker-tag: '${{ github.event.pull_request.head.sha }}'
      secrets: inherit
