name: CI/CD on PR

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      QUAY_USERNAME:
        required: true
      QUAY_TOKEN:
        required: true

jobs:
  cd-dev:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: decentraland/actions/.github/workflows/build-quay-main.yml@main
    secrets: inherit
